// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CanService.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CanService.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace COWA {
namespace CanService {
class CanDataDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CanData> {
} _CanData_default_instance_;
class CanServiceMsgDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CanServiceMsg> {
} _CanServiceMsg_default_instance_;

namespace protobuf_CanService_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanData, canid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanData, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanServiceMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanServiceMsg, eventid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanServiceMsg, seqnum_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanServiceMsg, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CanServiceMsg, candata_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CanData)},
  { 7, -1, sizeof(CanServiceMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CanData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CanServiceMsg_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "CanService.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _CanData_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _CanServiceMsg_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CanData_default_instance_.DefaultConstruct();
  _CanServiceMsg_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020CanService.proto\022\017COWA.CanService\"&\n\007C"
      "anData\022\r\n\005canId\030\001 \001(\r\022\014\n\004data\030\002 \001(\014\"n\n\rC"
      "anServiceMsg\022\017\n\007eventId\030\001 \001(\r\022\016\n\006seqNum\030"
      "\002 \001(\r\022\021\n\ttimestamp\030\003 \001(\004\022)\n\007canData\030\004 \003("
      "\0132\030.COWA.CanService.CanData*|\n\007EventId\022\024"
      "\n\020EVENT_ID_INVALID\020\000\022\031\n\025EVENT_ID_SET_CAN"
      "_DATA\020\001\022\035\n\031EVENT_ID_HMI_GET_CAN_DATA\020\002\022!"
      "\n\035EVENT_ID_HMI_GET_NETWORK_DATA\020\003b\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 321);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CanService.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_CanService_2eproto

const ::google::protobuf::EnumDescriptor* EventId_descriptor() {
  protobuf_CanService_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CanService_2eproto::file_level_enum_descriptors[0];
}
bool EventId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CanData::kCanIdFieldNumber;
const int CanData::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CanData::CanData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CanService_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:COWA.CanService.CanData)
}
CanData::CanData(const CanData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  canid_ = from.canid_;
  // @@protoc_insertion_point(copy_constructor:COWA.CanService.CanData)
}

void CanData::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  canid_ = 0u;
  _cached_size_ = 0;
}

CanData::~CanData() {
  // @@protoc_insertion_point(destructor:COWA.CanService.CanData)
  SharedDtor();
}

void CanData::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CanData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CanData::descriptor() {
  protobuf_CanService_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CanService_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CanData& CanData::default_instance() {
  protobuf_CanService_2eproto::InitDefaults();
  return *internal_default_instance();
}

CanData* CanData::New(::google::protobuf::Arena* arena) const {
  CanData* n = new CanData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CanData::Clear() {
// @@protoc_insertion_point(message_clear_start:COWA.CanService.CanData)
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  canid_ = 0u;
}

bool CanData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:COWA.CanService.CanData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 canId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &canid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:COWA.CanService.CanData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:COWA.CanService.CanData)
  return false;
#undef DO_
}

void CanData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:COWA.CanService.CanData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 canId = 1;
  if (this->canid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->canid(), output);
  }

  // bytes data = 2;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:COWA.CanService.CanData)
}

::google::protobuf::uint8* CanData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:COWA.CanService.CanData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 canId = 1;
  if (this->canid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->canid(), target);
  }

  // bytes data = 2;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:COWA.CanService.CanData)
  return target;
}

size_t CanData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:COWA.CanService.CanData)
  size_t total_size = 0;

  // bytes data = 2;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // uint32 canId = 1;
  if (this->canid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->canid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CanData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:COWA.CanService.CanData)
  GOOGLE_DCHECK_NE(&from, this);
  const CanData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CanData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:COWA.CanService.CanData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:COWA.CanService.CanData)
    MergeFrom(*source);
  }
}

void CanData::MergeFrom(const CanData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:COWA.CanService.CanData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.canid() != 0) {
    set_canid(from.canid());
  }
}

void CanData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:COWA.CanService.CanData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CanData::CopyFrom(const CanData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COWA.CanService.CanData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CanData::IsInitialized() const {
  return true;
}

void CanData::Swap(CanData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CanData::InternalSwap(CanData* other) {
  data_.Swap(&other->data_);
  std::swap(canid_, other->canid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CanData::GetMetadata() const {
  protobuf_CanService_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CanService_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CanData

// uint32 canId = 1;
void CanData::clear_canid() {
  canid_ = 0u;
}
::google::protobuf::uint32 CanData::canid() const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanData.canId)
  return canid_;
}
void CanData::set_canid(::google::protobuf::uint32 value) {
  
  canid_ = value;
  // @@protoc_insertion_point(field_set:COWA.CanService.CanData.canId)
}

// bytes data = 2;
void CanData::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CanData::data() const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanData.data)
  return data_.GetNoArena();
}
void CanData::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:COWA.CanService.CanData.data)
}
#if LANG_CXX11
void CanData::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:COWA.CanService.CanData.data)
}
#endif
void CanData::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:COWA.CanService.CanData.data)
}
void CanData::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:COWA.CanService.CanData.data)
}
::std::string* CanData::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:COWA.CanService.CanData.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CanData::release_data() {
  // @@protoc_insertion_point(field_release:COWA.CanService.CanData.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CanData::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:COWA.CanService.CanData.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CanServiceMsg::kEventIdFieldNumber;
const int CanServiceMsg::kSeqNumFieldNumber;
const int CanServiceMsg::kTimestampFieldNumber;
const int CanServiceMsg::kCanDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CanServiceMsg::CanServiceMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CanService_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:COWA.CanService.CanServiceMsg)
}
CanServiceMsg::CanServiceMsg(const CanServiceMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      candata_(from.candata_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&eventid_, &from.eventid_,
    reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&eventid_) + sizeof(timestamp_));
  // @@protoc_insertion_point(copy_constructor:COWA.CanService.CanServiceMsg)
}

void CanServiceMsg::SharedCtor() {
  ::memset(&eventid_, 0, reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&eventid_) + sizeof(timestamp_));
  _cached_size_ = 0;
}

CanServiceMsg::~CanServiceMsg() {
  // @@protoc_insertion_point(destructor:COWA.CanService.CanServiceMsg)
  SharedDtor();
}

void CanServiceMsg::SharedDtor() {
}

void CanServiceMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CanServiceMsg::descriptor() {
  protobuf_CanService_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CanService_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CanServiceMsg& CanServiceMsg::default_instance() {
  protobuf_CanService_2eproto::InitDefaults();
  return *internal_default_instance();
}

CanServiceMsg* CanServiceMsg::New(::google::protobuf::Arena* arena) const {
  CanServiceMsg* n = new CanServiceMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CanServiceMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:COWA.CanService.CanServiceMsg)
  candata_.Clear();
  ::memset(&eventid_, 0, reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&eventid_) + sizeof(timestamp_));
}

bool CanServiceMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:COWA.CanService.CanServiceMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 eventId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &eventid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 seqNum = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seqnum_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .COWA.CanService.CanData canData = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_candata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:COWA.CanService.CanServiceMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:COWA.CanService.CanServiceMsg)
  return false;
#undef DO_
}

void CanServiceMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:COWA.CanService.CanServiceMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 eventId = 1;
  if (this->eventid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->eventid(), output);
  }

  // uint32 seqNum = 2;
  if (this->seqnum() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->seqnum(), output);
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->timestamp(), output);
  }

  // repeated .COWA.CanService.CanData canData = 4;
  for (unsigned int i = 0, n = this->candata_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->candata(i), output);
  }

  // @@protoc_insertion_point(serialize_end:COWA.CanService.CanServiceMsg)
}

::google::protobuf::uint8* CanServiceMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:COWA.CanService.CanServiceMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 eventId = 1;
  if (this->eventid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->eventid(), target);
  }

  // uint32 seqNum = 2;
  if (this->seqnum() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->seqnum(), target);
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->timestamp(), target);
  }

  // repeated .COWA.CanService.CanData canData = 4;
  for (unsigned int i = 0, n = this->candata_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->candata(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:COWA.CanService.CanServiceMsg)
  return target;
}

size_t CanServiceMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:COWA.CanService.CanServiceMsg)
  size_t total_size = 0;

  // repeated .COWA.CanService.CanData canData = 4;
  {
    unsigned int count = this->candata_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->candata(i));
    }
  }

  // uint32 eventId = 1;
  if (this->eventid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->eventid());
  }

  // uint32 seqNum = 2;
  if (this->seqnum() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->seqnum());
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CanServiceMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:COWA.CanService.CanServiceMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const CanServiceMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CanServiceMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:COWA.CanService.CanServiceMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:COWA.CanService.CanServiceMsg)
    MergeFrom(*source);
  }
}

void CanServiceMsg::MergeFrom(const CanServiceMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:COWA.CanService.CanServiceMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  candata_.MergeFrom(from.candata_);
  if (from.eventid() != 0) {
    set_eventid(from.eventid());
  }
  if (from.seqnum() != 0) {
    set_seqnum(from.seqnum());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void CanServiceMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:COWA.CanService.CanServiceMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CanServiceMsg::CopyFrom(const CanServiceMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COWA.CanService.CanServiceMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CanServiceMsg::IsInitialized() const {
  return true;
}

void CanServiceMsg::Swap(CanServiceMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CanServiceMsg::InternalSwap(CanServiceMsg* other) {
  candata_.InternalSwap(&other->candata_);
  std::swap(eventid_, other->eventid_);
  std::swap(seqnum_, other->seqnum_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CanServiceMsg::GetMetadata() const {
  protobuf_CanService_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CanService_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CanServiceMsg

// uint32 eventId = 1;
void CanServiceMsg::clear_eventid() {
  eventid_ = 0u;
}
::google::protobuf::uint32 CanServiceMsg::eventid() const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanServiceMsg.eventId)
  return eventid_;
}
void CanServiceMsg::set_eventid(::google::protobuf::uint32 value) {
  
  eventid_ = value;
  // @@protoc_insertion_point(field_set:COWA.CanService.CanServiceMsg.eventId)
}

// uint32 seqNum = 2;
void CanServiceMsg::clear_seqnum() {
  seqnum_ = 0u;
}
::google::protobuf::uint32 CanServiceMsg::seqnum() const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanServiceMsg.seqNum)
  return seqnum_;
}
void CanServiceMsg::set_seqnum(::google::protobuf::uint32 value) {
  
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:COWA.CanService.CanServiceMsg.seqNum)
}

// uint64 timestamp = 3;
void CanServiceMsg::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 CanServiceMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanServiceMsg.timestamp)
  return timestamp_;
}
void CanServiceMsg::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:COWA.CanService.CanServiceMsg.timestamp)
}

// repeated .COWA.CanService.CanData canData = 4;
int CanServiceMsg::candata_size() const {
  return candata_.size();
}
void CanServiceMsg::clear_candata() {
  candata_.Clear();
}
const ::COWA::CanService::CanData& CanServiceMsg::candata(int index) const {
  // @@protoc_insertion_point(field_get:COWA.CanService.CanServiceMsg.canData)
  return candata_.Get(index);
}
::COWA::CanService::CanData* CanServiceMsg::mutable_candata(int index) {
  // @@protoc_insertion_point(field_mutable:COWA.CanService.CanServiceMsg.canData)
  return candata_.Mutable(index);
}
::COWA::CanService::CanData* CanServiceMsg::add_candata() {
  // @@protoc_insertion_point(field_add:COWA.CanService.CanServiceMsg.canData)
  return candata_.Add();
}
::google::protobuf::RepeatedPtrField< ::COWA::CanService::CanData >*
CanServiceMsg::mutable_candata() {
  // @@protoc_insertion_point(field_mutable_list:COWA.CanService.CanServiceMsg.canData)
  return &candata_;
}
const ::google::protobuf::RepeatedPtrField< ::COWA::CanService::CanData >&
CanServiceMsg::candata() const {
  // @@protoc_insertion_point(field_list:COWA.CanService.CanServiceMsg.canData)
  return candata_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CanService
}  // namespace COWA

// @@protoc_insertion_point(global_scope)
