// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

#ifndef PROTOBUF_Network_2eproto__INCLUDED
#define PROTOBUF_Network_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace COWA {
namespace Network {
class Moderm;
class ModermDefaultTypeInternal;
extern ModermDefaultTypeInternal _Moderm_default_instance_;
}  // namespace Network
}  // namespace COWA

namespace COWA {
namespace Network {

namespace protobuf_Network_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Network_2eproto

// ===================================================================

class Moderm : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:COWA.Network.Moderm) */ {
 public:
  Moderm();
  virtual ~Moderm();

  Moderm(const Moderm& from);

  inline Moderm& operator=(const Moderm& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Moderm& default_instance();

  static inline const Moderm* internal_default_instance() {
    return reinterpret_cast<const Moderm*>(
               &_Moderm_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Moderm* other);

  // implements Message ----------------------------------------------

  inline Moderm* New() const PROTOBUF_FINAL { return New(NULL); }

  Moderm* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Moderm& from);
  void MergeFrom(const Moderm& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Moderm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string CSQ = 2;
  void clear_csq();
  static const int kCSQFieldNumber = 2;
  const ::std::string& csq() const;
  void set_csq(const ::std::string& value);
  #if LANG_CXX11
  void set_csq(::std::string&& value);
  #endif
  void set_csq(const char* value);
  void set_csq(const char* value, size_t size);
  ::std::string* mutable_csq();
  ::std::string* release_csq();
  void set_allocated_csq(::std::string* csq);

  // string COPS = 3;
  void clear_cops();
  static const int kCOPSFieldNumber = 3;
  const ::std::string& cops() const;
  void set_cops(const ::std::string& value);
  #if LANG_CXX11
  void set_cops(::std::string&& value);
  #endif
  void set_cops(const char* value);
  void set_cops(const char* value, size_t size);
  ::std::string* mutable_cops();
  ::std::string* release_cops();
  void set_allocated_cops(::std::string* cops);

  // string CGREG = 4;
  void clear_cgreg();
  static const int kCGREGFieldNumber = 4;
  const ::std::string& cgreg() const;
  void set_cgreg(const ::std::string& value);
  #if LANG_CXX11
  void set_cgreg(::std::string&& value);
  #endif
  void set_cgreg(const char* value);
  void set_cgreg(const char* value, size_t size);
  ::std::string* mutable_cgreg();
  ::std::string* release_cgreg();
  void set_allocated_cgreg(::std::string* cgreg);

  // int32 slot = 1;
  void clear_slot();
  static const int kSlotFieldNumber = 1;
  ::google::protobuf::int32 slot() const;
  void set_slot(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:COWA.Network.Moderm)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr csq_;
  ::google::protobuf::internal::ArenaStringPtr cops_;
  ::google::protobuf::internal::ArenaStringPtr cgreg_;
  ::google::protobuf::int32 slot_;
  mutable int _cached_size_;
  friend struct protobuf_Network_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Moderm

// int32 slot = 1;
inline void Moderm::clear_slot() {
  slot_ = 0;
}
inline ::google::protobuf::int32 Moderm::slot() const {
  // @@protoc_insertion_point(field_get:COWA.Network.Moderm.slot)
  return slot_;
}
inline void Moderm::set_slot(::google::protobuf::int32 value) {
  
  slot_ = value;
  // @@protoc_insertion_point(field_set:COWA.Network.Moderm.slot)
}

// string CSQ = 2;
inline void Moderm::clear_csq() {
  csq_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Moderm::csq() const {
  // @@protoc_insertion_point(field_get:COWA.Network.Moderm.CSQ)
  return csq_.GetNoArena();
}
inline void Moderm::set_csq(const ::std::string& value) {
  
  csq_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:COWA.Network.Moderm.CSQ)
}
#if LANG_CXX11
inline void Moderm::set_csq(::std::string&& value) {
  
  csq_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:COWA.Network.Moderm.CSQ)
}
#endif
inline void Moderm::set_csq(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  csq_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:COWA.Network.Moderm.CSQ)
}
inline void Moderm::set_csq(const char* value, size_t size) {
  
  csq_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:COWA.Network.Moderm.CSQ)
}
inline ::std::string* Moderm::mutable_csq() {
  
  // @@protoc_insertion_point(field_mutable:COWA.Network.Moderm.CSQ)
  return csq_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Moderm::release_csq() {
  // @@protoc_insertion_point(field_release:COWA.Network.Moderm.CSQ)
  
  return csq_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Moderm::set_allocated_csq(::std::string* csq) {
  if (csq != NULL) {
    
  } else {
    
  }
  csq_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), csq);
  // @@protoc_insertion_point(field_set_allocated:COWA.Network.Moderm.CSQ)
}

// string COPS = 3;
inline void Moderm::clear_cops() {
  cops_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Moderm::cops() const {
  // @@protoc_insertion_point(field_get:COWA.Network.Moderm.COPS)
  return cops_.GetNoArena();
}
inline void Moderm::set_cops(const ::std::string& value) {
  
  cops_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:COWA.Network.Moderm.COPS)
}
#if LANG_CXX11
inline void Moderm::set_cops(::std::string&& value) {
  
  cops_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:COWA.Network.Moderm.COPS)
}
#endif
inline void Moderm::set_cops(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cops_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:COWA.Network.Moderm.COPS)
}
inline void Moderm::set_cops(const char* value, size_t size) {
  
  cops_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:COWA.Network.Moderm.COPS)
}
inline ::std::string* Moderm::mutable_cops() {
  
  // @@protoc_insertion_point(field_mutable:COWA.Network.Moderm.COPS)
  return cops_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Moderm::release_cops() {
  // @@protoc_insertion_point(field_release:COWA.Network.Moderm.COPS)
  
  return cops_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Moderm::set_allocated_cops(::std::string* cops) {
  if (cops != NULL) {
    
  } else {
    
  }
  cops_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cops);
  // @@protoc_insertion_point(field_set_allocated:COWA.Network.Moderm.COPS)
}

// string CGREG = 4;
inline void Moderm::clear_cgreg() {
  cgreg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Moderm::cgreg() const {
  // @@protoc_insertion_point(field_get:COWA.Network.Moderm.CGREG)
  return cgreg_.GetNoArena();
}
inline void Moderm::set_cgreg(const ::std::string& value) {
  
  cgreg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:COWA.Network.Moderm.CGREG)
}
#if LANG_CXX11
inline void Moderm::set_cgreg(::std::string&& value) {
  
  cgreg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:COWA.Network.Moderm.CGREG)
}
#endif
inline void Moderm::set_cgreg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cgreg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:COWA.Network.Moderm.CGREG)
}
inline void Moderm::set_cgreg(const char* value, size_t size) {
  
  cgreg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:COWA.Network.Moderm.CGREG)
}
inline ::std::string* Moderm::mutable_cgreg() {
  
  // @@protoc_insertion_point(field_mutable:COWA.Network.Moderm.CGREG)
  return cgreg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Moderm::release_cgreg() {
  // @@protoc_insertion_point(field_release:COWA.Network.Moderm.CGREG)
  
  return cgreg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Moderm::set_allocated_cgreg(::std::string* cgreg) {
  if (cgreg != NULL) {
    
  } else {
    
  }
  cgreg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cgreg);
  // @@protoc_insertion_point(field_set_allocated:COWA.Network.Moderm.CGREG)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace Network
}  // namespace COWA

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Network_2eproto__INCLUDED
