#pragma once

#include <cstdint>
#include <cppgl.h>

#include <QOpenGLContext>
#include <QOpenGLExtraFunctions>

class QtGLES3 : public cppgl::CppGL
{
public:
	QtGLES3();
	QtGLES3(QOpenGLContext* context);
	~QtGLES3();
	
public:
	cppgl::GLSLVersion GetGLSLVersion() override;
	void BindTexture(cppgl::enumeration target, cppgl::uint texture) override;
	void BlendFunc(cppgl::enumeration sfactor, cppgl::enumeration dfactor) override;
	void Clear(cppgl::bitfield mask) override;
	void ClearColor(cppgl::clampf red, cppgl::clampf green, cppgl::clampf blue, cppgl::clampf alpha) override;
	void ClearStencil(int s) override;
	void ColorMask(cppgl::boolean red, cppgl::boolean green, cppgl::boolean blue, cppgl::boolean alpha) override;
	void CopyTexImage2D(cppgl::enumeration target, int level, cppgl::enumeration internalformat, int x, int y, cppgl::sizei width, cppgl::sizei height, int border) override;
	void CopyTexSubImage2D(cppgl::enumeration target, int level, int xoffset, int yoffset, int x, int y, cppgl::sizei width, cppgl::sizei height) override;
	void CullFace(cppgl::enumeration mode) override;
	void DeleteTextures(cppgl::sizei n, const cppgl::uint* textures) override;
	void DepthFunc(cppgl::enumeration func) override;
	void DepthMask(cppgl::boolean flag) override;
	void Disable(cppgl::enumeration cap) override;
	void DrawArrays(cppgl::enumeration mode, int first, cppgl::sizei count) override;
	void DrawElements(cppgl::enumeration mode, cppgl::sizei count, cppgl::enumeration type, const void* indices) override;
	void Enable(cppgl::enumeration cap) override;
	void Finish() override;
	void Flush() override;
	void FrontFace(cppgl::enumeration mode) override;
	void GenTextures(cppgl::sizei n, cppgl::uint* textures) override;
	void GetBooleanv(cppgl::enumeration pname, cppgl::boolean* params) override;
	cppgl::enumeration GetError() override;
	void GetFloatv(cppgl::enumeration pname, float* params) override;
	void GetIntegerv(cppgl::enumeration pname, int* params) override;
	const cppgl::ubyte* GetString(cppgl::enumeration name) override;
	void GetTexParameterfv(cppgl::enumeration target, cppgl::enumeration pname, float* params) override;
	void GetTexParameteriv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void Hint(cppgl::enumeration target, cppgl::enumeration mode) override;
	cppgl::boolean IsEnabled(cppgl::enumeration cap) override;
	cppgl::boolean IsTexture(cppgl::uint texture) override;
	void LineWidth(float width) override;
	void PixelStorei(cppgl::enumeration pname, int param) override;
	void PolygonOffset(float factor, float units) override;
	void ReadPixels(int x, int y, cppgl::sizei width, cppgl::sizei height, cppgl::enumeration format, cppgl::enumeration type, void* pixels) override;
	void Scissor(int x, int y, cppgl::sizei width, cppgl::sizei height) override;
	void StencilFunc(cppgl::enumeration func, int ref, cppgl::uint mask) override;
	void StencilMask(cppgl::uint mask) override;
	void StencilOp(cppgl::enumeration fail, cppgl::enumeration zfail, cppgl::enumeration zpass) override;
	void TexImage2D(cppgl::enumeration target, int level, int internalformat, cppgl::sizei width, cppgl::sizei height, int border, cppgl::enumeration format, cppgl::enumeration type, const void* pixels) override;
	void TexParameterf(cppgl::enumeration target, cppgl::enumeration pname, float param) override;
	void TexParameterfv(cppgl::enumeration target, cppgl::enumeration pname, const float* params) override;
	void TexParameteri(cppgl::enumeration target, cppgl::enumeration pname, int param) override;
	void TexParameteriv(cppgl::enumeration target, cppgl::enumeration pname, const int* params) override;
	void TexSubImage2D(cppgl::enumeration target, int level, int xoffset, int yoffset, cppgl::sizei width, cppgl::sizei height, cppgl::enumeration format, cppgl::enumeration type, const void* pixels) override;
	void Viewport(int x, int y, cppgl::sizei width, cppgl::sizei height) override;
	void ActiveTexture(cppgl::enumeration texture) override;
	void AttachShader(cppgl::uint program, cppgl::uint shader) override;
	void BindAttribLocation(cppgl::uint program, cppgl::uint index, const char* name) override;
	void BindBuffer(cppgl::enumeration target, cppgl::uint buffer) override;
	void BindFramebuffer(cppgl::enumeration target, cppgl::uint framebuffer) override;
	void BindRenderbuffer(cppgl::enumeration target, cppgl::uint renderbuffer) override;
	void BlendColor(cppgl::clampf red, cppgl::clampf green, cppgl::clampf blue, cppgl::clampf alpha) override;
	void BlendEquation(cppgl::enumeration mode) override;
	void BlendEquationSeparate(cppgl::enumeration modeRGB, cppgl::enumeration modeAlpha) override;
	void BlendFuncSeparate(cppgl::enumeration srcRGB, cppgl::enumeration dstRGB, cppgl::enumeration srcAlpha, cppgl::enumeration dstAlpha) override;
	void BufferData(cppgl::enumeration target, cppgl::sizeiptr size, const void* data, cppgl::enumeration usage) override;
	void BufferSubData(cppgl::enumeration target, cppgl::intptr offset, cppgl::sizeiptr size, const void* data) override;
	cppgl::enumeration CheckFramebufferStatus(cppgl::enumeration target) override;
	void ClearDepthf(cppgl::clampf depth) override;
	void CompileShader(cppgl::uint shader) override;
	void CompressedTexImage2D(cppgl::enumeration target, int level, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height, int border, cppgl::sizei imageSize, const void* data) override;
	void CompressedTexSubImage2D(cppgl::enumeration target, int level, int xoffset, int yoffset, cppgl::sizei width, cppgl::sizei height, cppgl::enumeration format, cppgl::sizei imageSize, const void* data) override;
	cppgl::uint CreateProgram() override;
	cppgl::uint CreateShader(cppgl::enumeration type) override;
	void DeleteBuffers(cppgl::sizei n, const cppgl::uint* buffers) override;
	void DeleteFramebuffers(cppgl::sizei n, const cppgl::uint* framebuffers) override;
	void DeleteProgram(cppgl::uint program) override;
	void DeleteRenderbuffers(cppgl::sizei n, const cppgl::uint* renderbuffers) override;
	void DeleteShader(cppgl::uint shader) override;
	void DepthRangef(cppgl::clampf zNear, cppgl::clampf zFar) override;
	void DetachShader(cppgl::uint program, cppgl::uint shader) override;
	void DisableVertexAttribArray(cppgl::uint index) override;
	void EnableVertexAttribArray(cppgl::uint index) override;
	void FramebufferRenderbuffer(cppgl::enumeration target, cppgl::enumeration attachment, cppgl::enumeration renderbuffertarget, cppgl::uint renderbuffer) override;
	void FramebufferTexture2D(cppgl::enumeration target, cppgl::enumeration attachment, cppgl::enumeration textarget, cppgl::uint texture, int level) override;
	void GenBuffers(cppgl::sizei n, cppgl::uint* buffers) override;
	void GenerateMipmap(cppgl::enumeration target) override;
	void GenFramebuffers(cppgl::sizei n, cppgl::uint* framebuffers) override;
	void GenRenderbuffers(cppgl::sizei n, cppgl::uint* renderbuffers) override;
	void GetActiveAttrib(cppgl::uint program, cppgl::uint index, cppgl::sizei bufsize, cppgl::sizei* length, int* size, cppgl::enumeration* type, char* name) override;
	void GetActiveUniform(cppgl::uint program, cppgl::uint index, cppgl::sizei bufsize, cppgl::sizei* length, int* size, cppgl::enumeration* type, char* name) override;
	void GetAttachedShaders(cppgl::uint program, cppgl::sizei maxcount, cppgl::sizei* count, cppgl::uint* shaders) override;
	int GetAttribLocation(cppgl::uint program, const char* name) override;
	void GetBufferParameteriv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void GetFramebufferAttachmentParameteriv(cppgl::enumeration target, cppgl::enumeration attachment, cppgl::enumeration pname, int* params) override;
	void GetProgramiv(cppgl::uint program, cppgl::enumeration pname, int* params) override;
	void GetProgramInfoLog(cppgl::uint program, cppgl::sizei bufsize, cppgl::sizei* length, char* infolog) override;
	void GetRenderbufferParameteriv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void GetShaderiv(cppgl::uint shader, cppgl::enumeration pname, int* params) override;
	void GetShaderInfoLog(cppgl::uint shader, cppgl::sizei bufsize, cppgl::sizei* length, char* infolog) override;
	void GetShaderPrecisionFormat(cppgl::enumeration shadertype, cppgl::enumeration precisiontype, int* range, int* precision) override;
	void GetShaderSource(cppgl::uint shader, cppgl::sizei bufsize, cppgl::sizei* length, char* source) override;
	void GetUniformfv(cppgl::uint program, int location, float* params) override;
	void GetUniformiv(cppgl::uint program, int location, int* params) override;
	int GetUniformLocation(cppgl::uint program, const char* name) override;
	void GetVertexAttribfv(cppgl::uint index, cppgl::enumeration pname, float* params) override;
	void GetVertexAttribiv(cppgl::uint index, cppgl::enumeration pname, int* params) override;
	void GetVertexAttribPointerv(cppgl::uint index, cppgl::enumeration pname, void** pointer) override;
	cppgl::boolean IsBuffer(cppgl::uint buffer) override;
	cppgl::boolean IsFramebuffer(cppgl::uint framebuffer) override;
	cppgl::boolean IsProgram(cppgl::uint program) override;
	cppgl::boolean IsRenderbuffer(cppgl::uint renderbuffer) override;
	cppgl::boolean IsShader(cppgl::uint shader) override;
	void LinkProgram(cppgl::uint program) override;
	void ReleaseShaderCompiler() override;
	void RenderbufferStorage(cppgl::enumeration target, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height) override;
	void SampleCoverage(cppgl::clampf value, cppgl::boolean invert) override;
	void ShaderBinary(int n, const cppgl::uint* shaders, cppgl::enumeration binaryformat, const void* binary, int length) override;
	void ShaderSource(cppgl::uint shader, cppgl::sizei count, const char** string, const int* length) override;
	void StencilFuncSeparate(cppgl::enumeration face, cppgl::enumeration func, int ref, cppgl::uint mask) override;
	void StencilMaskSeparate(cppgl::enumeration face, cppgl::uint mask) override;
	void StencilOpSeparate(cppgl::enumeration face, cppgl::enumeration fail, cppgl::enumeration zfail, cppgl::enumeration zpass) override;
	void Uniform1f(int location, float x) override;
	void Uniform1fv(int location, cppgl::sizei count, const float* v) override;
	void Uniform1i(int location, int x) override;
	void Uniform1iv(int location, cppgl::sizei count, const int* v) override;
	void Uniform2f(int location, float x, float y) override;
	void Uniform2fv(int location, cppgl::sizei count, const float* v) override;
	void Uniform2i(int location, int x, int y) override;
	void Uniform2iv(int location, cppgl::sizei count, const int* v) override;
	void Uniform3f(int location, float x, float y, float z) override;
	void Uniform3fv(int location, cppgl::sizei count, const float* v) override;
	void Uniform3i(int location, int x, int y, int z) override;
	void Uniform3iv(int location, cppgl::sizei count, const int* v) override;
	void Uniform4f(int location, float x, float y, float z, float w) override;
	void Uniform4fv(int location, cppgl::sizei count, const float* v) override;
	void Uniform4i(int location, int x, int y, int z, int w) override;
	void Uniform4iv(int location, cppgl::sizei count, const int* v) override;
	void UniformMatrix2fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float* value) override;
	void UniformMatrix3fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float* value) override;
	void UniformMatrix4fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float* value) override;
	void UseProgram(cppgl::uint program) override;
	void ValidateProgram(cppgl::uint program) override;
	void VertexAttrib1f(cppgl::uint indx, float x) override;
	void VertexAttrib1fv(cppgl::uint indx, const float* values) override;
	void VertexAttrib2f(cppgl::uint indx, float x, float y) override;
	void VertexAttrib2fv(cppgl::uint indx, const float* values) override;
	void VertexAttrib3f(cppgl::uint indx, float x, float y, float z) override;
	void VertexAttrib3fv(cppgl::uint indx, const float* values) override;
	void VertexAttrib4f(cppgl::uint indx, float x, float y, float z, float w) override;
	void VertexAttrib4fv(cppgl::uint indx, const float* values) override;
	void VertexAttribPointer(cppgl::uint indx, int size, cppgl::enumeration type, cppgl::boolean normalized, cppgl::sizei stride, const void* ptr) override;
	void BeginQuery(cppgl::enumeration target, cppgl::uint id) override;
	void BeginTransformFeedback(cppgl::enumeration primitiveMode) override;
	void BindBufferBase(cppgl::enumeration target, cppgl::uint index, cppgl::uint buffer) override;
	void BindBufferRange(cppgl::enumeration target, cppgl::uint index, cppgl::uint buffer, cppgl::intptr offset, cppgl::sizeiptr size) override;
	void BindSampler(cppgl::uint unit, cppgl::uint sampler) override;
	void BindTransformFeedback(cppgl::enumeration target, cppgl::uint id) override;
	void BindVertexArray(cppgl::uint array) override;
	void BlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, cppgl::bitfield mask, cppgl::enumeration filter) override;
	void ClearBufferfi(cppgl::enumeration buffer, int drawbuffer, float depth, int stencil) override;
	void ClearBufferfv(cppgl::enumeration buffer, int drawbuffer, const float * value) override;
	void ClearBufferiv(cppgl::enumeration buffer, int drawbuffer, const int * value) override;
	void ClearBufferuiv(cppgl::enumeration buffer, int drawbuffer, const cppgl::uint * value) override;
	void CompressedTexImage3D(cppgl::enumeration target, int level, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth, int border, cppgl::sizei imageSize, const void * data) override;
	void CompressedTexSubImage3D(cppgl::enumeration target, int level, int xoffset, int yoffset, int zoffset, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth, cppgl::enumeration format, cppgl::sizei imageSize, const void * data) override;
	void CopyBufferSubData(cppgl::enumeration readTarget, cppgl::enumeration writeTarget, cppgl::intptr readOffset, cppgl::intptr writeOffset, cppgl::sizeiptr size) override;
	void CopyTexSubImage3D(cppgl::enumeration target, int level, int xoffset, int yoffset, int zoffset, int x, int y, cppgl::sizei width, cppgl::sizei height) override;
	void DeleteQueries(cppgl::sizei n, const cppgl::uint * ids) override;
	void DeleteSamplers(cppgl::sizei count, const cppgl::uint * samplers) override;
	void DeleteTransformFeedbacks(cppgl::sizei n, const cppgl::uint * ids) override;
	void DeleteVertexArrays(cppgl::sizei n, const cppgl::uint * arrays) override;
	void DrawArraysInstanced(cppgl::enumeration mode, int first, cppgl::sizei count, cppgl::sizei instancecount) override;
	void DrawBuffers(cppgl::sizei n, const cppgl::enumeration * bufs) override;
	void DrawElementsInstanced(cppgl::enumeration mode, cppgl::sizei count, cppgl::enumeration type, const void * indices, cppgl::sizei instancecount) override;
	void DrawRangeElements(cppgl::enumeration mode, cppgl::uint start, cppgl::uint end, cppgl::sizei count, cppgl::enumeration type, const void * indices) override;
	void EndQuery(cppgl::enumeration target) override;
	void EndTransformFeedback() override;
	void FlushMappedBufferRange(cppgl::enumeration target, cppgl::intptr offset, cppgl::sizeiptr length) override;
	void FramebufferTextureLayer(cppgl::enumeration target, cppgl::enumeration attachment, cppgl::uint texture, int level, int layer) override;
	void GenQueries(cppgl::sizei n, cppgl::uint* ids) override;
	void GenSamplers(cppgl::sizei count, cppgl::uint* samplers) override;
	void GenTransformFeedbacks(cppgl::sizei n, cppgl::uint* ids) override;
	void GenVertexArrays(cppgl::sizei n, cppgl::uint* arrays) override;
	void GetActiveUniformBlockName(cppgl::uint program, cppgl::uint uniformBlockIndex, cppgl::sizei bufSize, cppgl::sizei* length, char* uniformBlockName) override;
	void GetActiveUniformBlockiv(cppgl::uint program, cppgl::uint uniformBlockIndex, cppgl::enumeration pname, int* params) override;
	void GetActiveUniformsiv(cppgl::uint program, cppgl::sizei uniformCount, const cppgl::uint * uniformIndices, cppgl::enumeration pname, int* params) override;
	void GetBufferParameteri64v(cppgl::enumeration target, cppgl::enumeration pname, cppgl::int64* params) override;
	void GetBufferPointerv(cppgl::enumeration target, cppgl::enumeration pname, void ** params) override;
	int GetFragDataLocation(cppgl::uint program, const char * name) override;
	void GetInteger64i_v(cppgl::enumeration target, cppgl::uint index, cppgl::int64* data) override;
	void GetInteger64v(cppgl::enumeration pname, cppgl::int64* data) override;
	void GetIntegeri_v(cppgl::enumeration target, cppgl::uint index, int* data) override;
	void GetInternalformativ(cppgl::enumeration target, cppgl::enumeration internalformat, cppgl::enumeration pname, cppgl::sizei bufSize, int* params) override;
	void GetProgramBinary(cppgl::uint program, cppgl::sizei bufSize, cppgl::sizei* length, cppgl::enumeration* binaryFormat, void * binary) override;
	void GetQueryObjectuiv(cppgl::uint id, cppgl::enumeration pname, cppgl::uint* params) override;
	void GetQueryiv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void GetSamplerParameterfv(cppgl::uint sampler, cppgl::enumeration pname, float* params) override;
	void GetSamplerParameteriv(cppgl::uint sampler, cppgl::enumeration pname, int* params) override;
	const cppgl::ubyte * GetStringi(cppgl::enumeration name, cppgl::uint index) override;
	void GetTransformFeedbackVarying(cppgl::uint program, cppgl::uint index, cppgl::sizei bufSize, cppgl::sizei* length, cppgl::sizei* size, cppgl::enumeration* type, char* name) override;
	cppgl::uint GetUniformBlockIndex(cppgl::uint program, const char * uniformBlockName) override;
	void GetUniformIndices(cppgl::uint program, cppgl::sizei uniformCount, const char *const* uniformNames, cppgl::uint* uniformIndices) override;
	void GetUniformuiv(cppgl::uint program, int location, cppgl::uint* params) override;
	void GetVertexAttribIiv(cppgl::uint index, cppgl::enumeration pname, int* params) override;
	void GetVertexAttribIuiv(cppgl::uint index, cppgl::enumeration pname, cppgl::uint* params) override;
	void InvalidateFramebuffer(cppgl::enumeration target, cppgl::sizei numAttachments, const cppgl::enumeration * attachments) override;
	void InvalidateSubFramebuffer(cppgl::enumeration target, cppgl::sizei numAttachments, const cppgl::enumeration * attachments, int x, int y, cppgl::sizei width, cppgl::sizei height) override;
	cppgl::boolean IsQuery(cppgl::uint id) override;
	cppgl::boolean IsSampler(cppgl::uint sampler) override;
	cppgl::boolean IsTransformFeedback(cppgl::uint id) override;
	cppgl::boolean IsVertexArray(cppgl::uint array) override;
	void * MapBufferRange(cppgl::enumeration target, cppgl::intptr offset, cppgl::sizeiptr length, cppgl::bitfield access) override;
	void PauseTransformFeedback() override;
	void ProgramBinary(cppgl::uint program, cppgl::enumeration binaryFormat, const void * binary, cppgl::sizei length) override;
	void ProgramParameteri(cppgl::uint program, cppgl::enumeration pname, int value) override;
	void ReadBuffer(cppgl::enumeration src) override;
	void RenderbufferStorageMultisample(cppgl::enumeration target, cppgl::sizei samples, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height) override;
	void ResumeTransformFeedback() override;
	void SamplerParameterf(cppgl::uint sampler, cppgl::enumeration pname, float param) override;
	void SamplerParameterfv(cppgl::uint sampler, cppgl::enumeration pname, const float * param) override;
	void SamplerParameteri(cppgl::uint sampler, cppgl::enumeration pname, int param) override;
	void SamplerParameteriv(cppgl::uint sampler, cppgl::enumeration pname, const int * param) override;
	void TexImage3D(cppgl::enumeration target, int level, int internalformat, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth, int border, cppgl::enumeration format, cppgl::enumeration type, const void * pixels) override;
	void TexStorage2D(cppgl::enumeration target, cppgl::sizei levels, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height) override;
	void TexStorage3D(cppgl::enumeration target, cppgl::sizei levels, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth) override;
	void TexSubImage3D(cppgl::enumeration target, int level, int xoffset, int yoffset, int zoffset, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth, cppgl::enumeration format, cppgl::enumeration type, const void * pixels) override;
	void TransformFeedbackVaryings(cppgl::uint program, cppgl::sizei count, const char *const* varyings, cppgl::enumeration bufferMode) override;
	void Uniform1ui(int location, cppgl::uint v0) override;
	void Uniform1uiv(int location, cppgl::sizei count, const cppgl::uint * value) override;
	void Uniform2ui(int location, cppgl::uint v0, cppgl::uint v1) override;
	void Uniform2uiv(int location, cppgl::sizei count, const cppgl::uint * value) override;
	void Uniform3ui(int location, cppgl::uint v0, cppgl::uint v1, cppgl::uint v2) override;
	void Uniform3uiv(int location, cppgl::sizei count, const cppgl::uint * value) override;
	void Uniform4ui(int location, cppgl::uint v0, cppgl::uint v1, cppgl::uint v2, cppgl::uint v3) override;
	void Uniform4uiv(int location, cppgl::sizei count, const cppgl::uint * value) override;
	void UniformBlockBinding(cppgl::uint program, cppgl::uint uniformBlockIndex, cppgl::uint uniformBlockBinding) override;
	void UniformMatrix2x3fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void UniformMatrix2x4fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void UniformMatrix3x2fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void UniformMatrix3x4fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void UniformMatrix4x2fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void UniformMatrix4x3fv(int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	cppgl::boolean UnmapBuffer(cppgl::enumeration target) override;
	void VertexAttribDivisor(cppgl::uint index, cppgl::uint divisor) override;
	void VertexAttribI4i(cppgl::uint index, int x, int y, int z, int w) override;
	void VertexAttribI4iv(cppgl::uint index, const int * v) override;
	void VertexAttribI4ui(cppgl::uint index, cppgl::uint x, cppgl::uint y, cppgl::uint z, cppgl::uint w) override;
	void VertexAttribI4uiv(cppgl::uint index, const cppgl::uint * v) override;
	void VertexAttribIPointer(cppgl::uint index, int size, cppgl::enumeration type, cppgl::sizei stride, const void * pointer) override;
	void ActiveShaderProgram(cppgl::uint pipeline, cppgl::uint program) override;
	void BindImageTexture(cppgl::uint unit, cppgl::uint texture, int level, cppgl::boolean layered, int layer, cppgl::enumeration access, cppgl::enumeration format) override;
	void BindProgramPipeline(cppgl::uint pipeline) override;
	void BindVertexBuffer(cppgl::uint bindingindex, cppgl::uint buffer, cppgl::intptr offset, cppgl::sizei stride) override;
	cppgl::uint CreateShaderProgramv(cppgl::enumeration type, cppgl::sizei count, const char *const* strings) override;
	void DeleteProgramPipelines(cppgl::sizei n, const cppgl::uint * pipelines) override;
	void DispatchCompute(cppgl::uint num_groups_x, cppgl::uint num_groups_y, cppgl::uint num_groups_z) override;
	void DispatchComputeIndirect(cppgl::intptr indirect) override;
	void DrawArraysIndirect(cppgl::enumeration mode, const void * indirect) override;
	void DrawElementsIndirect(cppgl::enumeration mode, cppgl::enumeration type, const void * indirect) override;
	void FramebufferParameteri(cppgl::enumeration target, cppgl::enumeration pname, int param) override;
	void GenProgramPipelines(cppgl::sizei n, cppgl::uint* pipelines) override;
	void GetBooleani_v(cppgl::enumeration target, cppgl::uint index, cppgl::boolean* data) override;
	void GetFramebufferParameteriv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void GetMultisamplefv(cppgl::enumeration pname, cppgl::uint index, float* val) override;
	void GetProgramInterfaceiv(cppgl::uint program, cppgl::enumeration programInterface, cppgl::enumeration pname, int* params) override;
	void GetProgramPipelineInfoLog(cppgl::uint pipeline, cppgl::sizei bufSize, cppgl::sizei* length, char* infoLog) override;
	void GetProgramPipelineiv(cppgl::uint pipeline, cppgl::enumeration pname, int* params) override;
	cppgl::uint GetProgramResourceIndex(cppgl::uint program, cppgl::enumeration programInterface, const char * name) override;
	int GetProgramResourceLocation(cppgl::uint program, cppgl::enumeration programInterface, const char * name) override;
	void GetProgramResourceName(cppgl::uint program, cppgl::enumeration programInterface, cppgl::uint index, cppgl::sizei bufSize, cppgl::sizei* length, char* name) override;
	void GetProgramResourceiv(cppgl::uint program, cppgl::enumeration programInterface, cppgl::uint index, cppgl::sizei propCount, const cppgl::enumeration * props, cppgl::sizei bufSize, cppgl::sizei* length, int* params) override;
	void GetTexLevelParameterfv(cppgl::enumeration target, int level, cppgl::enumeration pname, float* params) override;
	void GetTexLevelParameteriv(cppgl::enumeration target, int level, cppgl::enumeration pname, int* params) override;
	cppgl::boolean IsProgramPipeline(cppgl::uint pipeline) override;
	void MemoryBarrierByRegion(cppgl::bitfield barriers) override;
	void ProgramUniform1f(cppgl::uint program, int location, float v0) override;
	void ProgramUniform1fv(cppgl::uint program, int location, cppgl::sizei count, const float * value) override;
	void ProgramUniform1i(cppgl::uint program, int location, int v0) override;
	void ProgramUniform1iv(cppgl::uint program, int location, cppgl::sizei count, const int * value) override;
	void ProgramUniform1ui(cppgl::uint program, int location, cppgl::uint v0) override;
	void ProgramUniform1uiv(cppgl::uint program, int location, cppgl::sizei count, const cppgl::uint * value) override;
	void ProgramUniform2f(cppgl::uint program, int location, float v0, float v1) override;
	void ProgramUniform2fv(cppgl::uint program, int location, cppgl::sizei count, const float * value) override;
	void ProgramUniform2i(cppgl::uint program, int location, int v0, int v1) override;
	void ProgramUniform2iv(cppgl::uint program, int location, cppgl::sizei count, const int * value) override;
	void ProgramUniform2ui(cppgl::uint program, int location, cppgl::uint v0, cppgl::uint v1) override;
	void ProgramUniform2uiv(cppgl::uint program, int location, cppgl::sizei count, const cppgl::uint * value) override;
	void ProgramUniform3f(cppgl::uint program, int location, float v0, float v1, float v2) override;
	void ProgramUniform3fv(cppgl::uint program, int location, cppgl::sizei count, const float * value) override;
	void ProgramUniform3i(cppgl::uint program, int location, int v0, int v1, int v2) override;
	void ProgramUniform3iv(cppgl::uint program, int location, cppgl::sizei count, const int * value) override;
	void ProgramUniform3ui(cppgl::uint program, int location, cppgl::uint v0, cppgl::uint v1, cppgl::uint v2) override;
	void ProgramUniform3uiv(cppgl::uint program, int location, cppgl::sizei count, const cppgl::uint * value) override;
	void ProgramUniform4f(cppgl::uint program, int location, float v0, float v1, float v2, float v3) override;
	void ProgramUniform4fv(cppgl::uint program, int location, cppgl::sizei count, const float * value) override;
	void ProgramUniform4i(cppgl::uint program, int location, int v0, int v1, int v2, int v3) override;
	void ProgramUniform4iv(cppgl::uint program, int location, cppgl::sizei count, const int * value) override;
	void ProgramUniform4ui(cppgl::uint program, int location, cppgl::uint v0, cppgl::uint v1, cppgl::uint v2, cppgl::uint v3) override;
	void ProgramUniform4uiv(cppgl::uint program, int location, cppgl::sizei count, const cppgl::uint * value) override;
	void ProgramUniformMatrix2fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix2x3fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix2x4fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix3fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix3x2fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix3x4fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix4fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix4x2fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void ProgramUniformMatrix4x3fv(cppgl::uint program, int location, cppgl::sizei count, cppgl::boolean transpose, const float * value) override;
	void SampleMaski(cppgl::uint maskNumber, cppgl::bitfield mask) override;
	void TexStorage2DMultisample(cppgl::enumeration target, cppgl::sizei samples, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height, cppgl::boolean fixedsamplelocations) override;
	void UseProgramStages(cppgl::uint pipeline, cppgl::bitfield stages, cppgl::uint program) override;
	void ValidateProgramPipeline(cppgl::uint pipeline) override;
	void VertexAttribBinding(cppgl::uint attribindex, cppgl::uint bindingindex) override;
	void VertexAttribFormat(cppgl::uint attribindex, int size, cppgl::enumeration type, cppgl::boolean normalized, cppgl::uint relativeoffset) override;
	void VertexAttribIFormat(cppgl::uint attribindex, int size, cppgl::enumeration type, cppgl::uint relativeoffset) override;
	void VertexBindingDivisor(cppgl::uint bindingindex, cppgl::uint divisor) override;
	void BlendBarrier() override;
	void BlendEquationSeparatei(cppgl::uint buf, cppgl::enumeration modeRGB, cppgl::enumeration modeAlpha) override;
	void BlendEquationi(cppgl::uint buf, cppgl::enumeration mode) override;
	void BlendFuncSeparatei(cppgl::uint buf, cppgl::enumeration srcRGB, cppgl::enumeration dstRGB, cppgl::enumeration srcAlpha, cppgl::enumeration dstAlpha) override;
	void BlendFunci(cppgl::uint buf, cppgl::enumeration src, cppgl::enumeration dst) override;
	void ColorMaski(cppgl::uint index, cppgl::boolean r, cppgl::boolean g, cppgl::boolean b, cppgl::boolean a) override;
	void CopyImageSubData(cppgl::uint srcName, cppgl::enumeration srcTarget, int srcLevel, int srcX, int srcY, int srcZ, cppgl::uint dstName, cppgl::enumeration dstTarget, int dstLevel, int dstX, int dstY, int dstZ, cppgl::sizei srcWidth, cppgl::sizei srcHeight, cppgl::sizei srcDepth) override;
	void DebugMessageCallback(cppgl::debugproc callback, const void * userParam) override;
	void DebugMessageControl(cppgl::enumeration source, cppgl::enumeration type, cppgl::enumeration severity, cppgl::sizei count, const cppgl::uint * ids, cppgl::boolean enabled) override;
	void DebugMessageInsert(cppgl::enumeration source, cppgl::enumeration type, cppgl::uint id, cppgl::enumeration severity, cppgl::sizei length, const char * buf) override;
	void Disablei(cppgl::enumeration target, cppgl::uint index) override;
	void DrawElementsBaseVertex(cppgl::enumeration mode, cppgl::sizei count, cppgl::enumeration type, const void * indices, int basevertex) override;
	void DrawElementsInstancedBaseVertex(cppgl::enumeration mode, cppgl::sizei count, cppgl::enumeration type, const void * indices, cppgl::sizei instancecount, int basevertex) override;
	void DrawRangeElementsBaseVertex(cppgl::enumeration mode, cppgl::uint start, cppgl::uint end, cppgl::sizei count, cppgl::enumeration type, const void * indices, int basevertex) override;
	void Enablei(cppgl::enumeration target, cppgl::uint index) override;
	void FramebufferTexture(cppgl::enumeration target, cppgl::enumeration attachment, cppgl::uint texture, int level) override;
	cppgl::uint GetDebugMessageLog(cppgl::uint count, cppgl::sizei bufSize, cppgl::enumeration* sources, cppgl::enumeration* types, cppgl::uint* ids, cppgl::enumeration* severities, cppgl::sizei* lengths, char* messageLog) override;
	cppgl::enumeration GetGraphicsResetStatus() override;
	void GetObjectLabel(cppgl::enumeration identifier, cppgl::uint name, cppgl::sizei bufSize, cppgl::sizei* length, char* label) override;
	void GetObjectPtrLabel(const void * ptr, cppgl::sizei bufSize, cppgl::sizei* length, char* label) override;
	void GetPointerv(cppgl::enumeration pname, void ** params) override;
	void GetSamplerParameterIiv(cppgl::uint sampler, cppgl::enumeration pname, int* params) override;
	void GetSamplerParameterIuiv(cppgl::uint sampler, cppgl::enumeration pname, cppgl::uint* params) override;
	void GetTexParameterIiv(cppgl::enumeration target, cppgl::enumeration pname, int* params) override;
	void GetTexParameterIuiv(cppgl::enumeration target, cppgl::enumeration pname, cppgl::uint* params) override;
	void GetnUniformfv(cppgl::uint program, int location, cppgl::sizei bufSize, float* params) override;
	void GetnUniformiv(cppgl::uint program, int location, cppgl::sizei bufSize, int* params) override;
	void GetnUniformuiv(cppgl::uint program, int location, cppgl::sizei bufSize, cppgl::uint* params) override;
	cppgl::boolean IsEnabledi(cppgl::enumeration target, cppgl::uint index) override;
	void MinSampleShading(float value) override;
	void ObjectLabel(cppgl::enumeration identifier, cppgl::uint name, cppgl::sizei length, const char * label) override;
	void ObjectPtrLabel(const void * ptr, cppgl::sizei length, const char * label) override;
	void PatchParameteri(cppgl::enumeration pname, int value) override;
	void PopDebugGroup() override;
	void PrimitiveBoundingBox(float minX, float minY, float minZ, float minW, float maxX, float maxY, float maxZ, float maxW) override;
	void PushDebugGroup(cppgl::enumeration source, cppgl::uint id, cppgl::sizei length, const char * message) override;
	void ReadnPixels(int x, int y, cppgl::sizei width, cppgl::sizei height, cppgl::enumeration format, cppgl::enumeration type, cppgl::sizei bufSize, void * data) override;
	void SamplerParameterIiv(cppgl::uint sampler, cppgl::enumeration pname, const int * param) override;
	void SamplerParameterIuiv(cppgl::uint sampler, cppgl::enumeration pname, const cppgl::uint * param) override;
	void TexBuffer(cppgl::enumeration target, cppgl::enumeration internalformat, cppgl::uint buffer) override;
	void TexBufferRange(cppgl::enumeration target, cppgl::enumeration internalformat, cppgl::uint buffer, cppgl::intptr offset, cppgl::sizeiptr size) override;
	void TexParameterIiv(cppgl::enumeration target, cppgl::enumeration pname, const int * params) override;
	void TexParameterIuiv(cppgl::enumeration target, cppgl::enumeration pname, const cppgl::uint * params) override;
	void TexStorage3DMultisample(cppgl::enumeration target, cppgl::sizei samples, cppgl::enumeration internalformat, cppgl::sizei width, cppgl::sizei height, cppgl::sizei depth, cppgl::boolean fixedsamplelocations) override;	
private:
	QOpenGLExtraFunctions *funs_;
};