// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_response.proto

#ifndef PROTOBUF_request_5fresponse_2eproto__INCLUDED
#define PROTOBUF_request_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "chassis.pb.h"
// @@protoc_insertion_point(includes)
namespace COWA {
namespace NavMsg {
class DebugField;
class DebugFieldDefaultTypeInternal;
extern DebugFieldDefaultTypeInternal _DebugField_default_instance_;
class VehicleBCM;
class VehicleBCMDefaultTypeInternal;
extern VehicleBCMDefaultTypeInternal _VehicleBCM_default_instance_;
class VehicleCommond;
class VehicleCommondDefaultTypeInternal;
extern VehicleCommondDefaultTypeInternal _VehicleCommond_default_instance_;
class VehicleDrive;
class VehicleDriveDefaultTypeInternal;
extern VehicleDriveDefaultTypeInternal _VehicleDrive_default_instance_;
class VehicleInfo;
class VehicleInfoDefaultTypeInternal;
extern VehicleInfoDefaultTypeInternal _VehicleInfo_default_instance_;
class VehicleSoc;
class VehicleSocDefaultTypeInternal;
extern VehicleSocDefaultTypeInternal _VehicleSoc_default_instance_;
}  // namespace NavMsg
}  // namespace COWA
namespace request_response {
class RequestResponseDataType;
class RequestResponseDataTypeDefaultTypeInternal;
extern RequestResponseDataTypeDefaultTypeInternal _RequestResponseDataType_default_instance_;
class ResponseStatusType;
class ResponseStatusTypeDefaultTypeInternal;
extern ResponseStatusTypeDefaultTypeInternal _ResponseStatusType_default_instance_;
class TargetCrvuePointType;
class TargetCrvuePointTypeDefaultTypeInternal;
extern TargetCrvuePointTypeDefaultTypeInternal _TargetCrvuePointType_default_instance_;
}  // namespace request_response

namespace request_response {

namespace protobuf_request_5fresponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_request_5fresponse_2eproto

enum ResponseStatusType_RequestStatusEnum {
  ResponseStatusType_RequestStatusEnum_NO_REQUEST = 0,
  ResponseStatusType_RequestStatusEnum_REQUEST_WAIT = 1,
  ResponseStatusType_RequestStatusEnum_REQUEST_SUCC = 2,
  ResponseStatusType_RequestStatusEnum_REQUEST_FAIL = 3,
  ResponseStatusType_RequestStatusEnum_RECEIVE_FAIL = 4
};
bool ResponseStatusType_RequestStatusEnum_IsValid(int value);
const ResponseStatusType_RequestStatusEnum ResponseStatusType_RequestStatusEnum_RequestStatusEnum_MIN = ResponseStatusType_RequestStatusEnum_NO_REQUEST;
const ResponseStatusType_RequestStatusEnum ResponseStatusType_RequestStatusEnum_RequestStatusEnum_MAX = ResponseStatusType_RequestStatusEnum_RECEIVE_FAIL;
const int ResponseStatusType_RequestStatusEnum_RequestStatusEnum_ARRAYSIZE = ResponseStatusType_RequestStatusEnum_RequestStatusEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* ResponseStatusType_RequestStatusEnum_descriptor();
inline const ::std::string& ResponseStatusType_RequestStatusEnum_Name(ResponseStatusType_RequestStatusEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    ResponseStatusType_RequestStatusEnum_descriptor(), value);
}
inline bool ResponseStatusType_RequestStatusEnum_Parse(
    const ::std::string& name, ResponseStatusType_RequestStatusEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResponseStatusType_RequestStatusEnum>(
    ResponseStatusType_RequestStatusEnum_descriptor(), name, value);
}
enum RequestResponseDataType_RequestType {
  RequestResponseDataType_RequestType_MIN_UNVAILD_TYPE = 0,
  RequestResponseDataType_RequestType_TARGET_CURVE_TYPE = 1,
  RequestResponseDataType_RequestType_ENABLE_AUTO_DRIVE_TYPE = 2,
  RequestResponseDataType_RequestType_ENABLE_CAMERA_TYPE = 3,
  RequestResponseDataType_RequestType_ENABLE_ORIGIN_POINT_CLOUD_TYPE = 4,
  RequestResponseDataType_RequestType_MAX_UNVAILD_TYPE = 5
};
bool RequestResponseDataType_RequestType_IsValid(int value);
const RequestResponseDataType_RequestType RequestResponseDataType_RequestType_RequestType_MIN = RequestResponseDataType_RequestType_MIN_UNVAILD_TYPE;
const RequestResponseDataType_RequestType RequestResponseDataType_RequestType_RequestType_MAX = RequestResponseDataType_RequestType_MAX_UNVAILD_TYPE;
const int RequestResponseDataType_RequestType_RequestType_ARRAYSIZE = RequestResponseDataType_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestResponseDataType_RequestType_descriptor();
inline const ::std::string& RequestResponseDataType_RequestType_Name(RequestResponseDataType_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestResponseDataType_RequestType_descriptor(), value);
}
inline bool RequestResponseDataType_RequestType_Parse(
    const ::std::string& name, RequestResponseDataType_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestResponseDataType_RequestType>(
    RequestResponseDataType_RequestType_descriptor(), name, value);
}
// ===================================================================

class TargetCrvuePointType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_response.TargetCrvuePointType) */ {
 public:
  TargetCrvuePointType();
  virtual ~TargetCrvuePointType();

  TargetCrvuePointType(const TargetCrvuePointType& from);

  inline TargetCrvuePointType& operator=(const TargetCrvuePointType& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TargetCrvuePointType& default_instance();

  static inline const TargetCrvuePointType* internal_default_instance() {
    return reinterpret_cast<const TargetCrvuePointType*>(
               &_TargetCrvuePointType_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TargetCrvuePointType* other);

  // implements Message ----------------------------------------------

  inline TargetCrvuePointType* New() const PROTOBUF_FINAL { return New(NULL); }

  TargetCrvuePointType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TargetCrvuePointType& from);
  void MergeFrom(const TargetCrvuePointType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TargetCrvuePointType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // @@protoc_insertion_point(class_scope:request_response.TargetCrvuePointType)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double x_;
  double y_;
  friend struct protobuf_request_5fresponse_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResponseStatusType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_response.ResponseStatusType) */ {
 public:
  ResponseStatusType();
  virtual ~ResponseStatusType();

  ResponseStatusType(const ResponseStatusType& from);

  inline ResponseStatusType& operator=(const ResponseStatusType& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseStatusType& default_instance();

  static inline const ResponseStatusType* internal_default_instance() {
    return reinterpret_cast<const ResponseStatusType*>(
               &_ResponseStatusType_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ResponseStatusType* other);

  // implements Message ----------------------------------------------

  inline ResponseStatusType* New() const PROTOBUF_FINAL { return New(NULL); }

  ResponseStatusType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResponseStatusType& from);
  void MergeFrom(const ResponseStatusType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResponseStatusType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ResponseStatusType_RequestStatusEnum RequestStatusEnum;
  static const RequestStatusEnum NO_REQUEST =
    ResponseStatusType_RequestStatusEnum_NO_REQUEST;
  static const RequestStatusEnum REQUEST_WAIT =
    ResponseStatusType_RequestStatusEnum_REQUEST_WAIT;
  static const RequestStatusEnum REQUEST_SUCC =
    ResponseStatusType_RequestStatusEnum_REQUEST_SUCC;
  static const RequestStatusEnum REQUEST_FAIL =
    ResponseStatusType_RequestStatusEnum_REQUEST_FAIL;
  static const RequestStatusEnum RECEIVE_FAIL =
    ResponseStatusType_RequestStatusEnum_RECEIVE_FAIL;
  static inline bool RequestStatusEnum_IsValid(int value) {
    return ResponseStatusType_RequestStatusEnum_IsValid(value);
  }
  static const RequestStatusEnum RequestStatusEnum_MIN =
    ResponseStatusType_RequestStatusEnum_RequestStatusEnum_MIN;
  static const RequestStatusEnum RequestStatusEnum_MAX =
    ResponseStatusType_RequestStatusEnum_RequestStatusEnum_MAX;
  static const int RequestStatusEnum_ARRAYSIZE =
    ResponseStatusType_RequestStatusEnum_RequestStatusEnum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestStatusEnum_descriptor() {
    return ResponseStatusType_RequestStatusEnum_descriptor();
  }
  static inline const ::std::string& RequestStatusEnum_Name(RequestStatusEnum value) {
    return ResponseStatusType_RequestStatusEnum_Name(value);
  }
  static inline bool RequestStatusEnum_Parse(const ::std::string& name,
      RequestStatusEnum* value) {
    return ResponseStatusType_RequestStatusEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string reponse_status_msg = 2;
  bool has_reponse_status_msg() const;
  void clear_reponse_status_msg();
  static const int kReponseStatusMsgFieldNumber = 2;
  const ::std::string& reponse_status_msg() const;
  void set_reponse_status_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_reponse_status_msg(::std::string&& value);
  #endif
  void set_reponse_status_msg(const char* value);
  void set_reponse_status_msg(const char* value, size_t size);
  ::std::string* mutable_reponse_status_msg();
  ::std::string* release_reponse_status_msg();
  void set_allocated_reponse_status_msg(::std::string* reponse_status_msg);

  // required .request_response.ResponseStatusType.RequestStatusEnum reponse_status_code = 1;
  bool has_reponse_status_code() const;
  void clear_reponse_status_code();
  static const int kReponseStatusCodeFieldNumber = 1;
  ::request_response::ResponseStatusType_RequestStatusEnum reponse_status_code() const;
  void set_reponse_status_code(::request_response::ResponseStatusType_RequestStatusEnum value);

  // @@protoc_insertion_point(class_scope:request_response.ResponseStatusType)
 private:
  void set_has_reponse_status_code();
  void clear_has_reponse_status_code();
  void set_has_reponse_status_msg();
  void clear_has_reponse_status_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr reponse_status_msg_;
  int reponse_status_code_;
  friend struct protobuf_request_5fresponse_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RequestResponseDataType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_response.RequestResponseDataType) */ {
 public:
  RequestResponseDataType();
  virtual ~RequestResponseDataType();

  RequestResponseDataType(const RequestResponseDataType& from);

  inline RequestResponseDataType& operator=(const RequestResponseDataType& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestResponseDataType& default_instance();

  static inline const RequestResponseDataType* internal_default_instance() {
    return reinterpret_cast<const RequestResponseDataType*>(
               &_RequestResponseDataType_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RequestResponseDataType* other);

  // implements Message ----------------------------------------------

  inline RequestResponseDataType* New() const PROTOBUF_FINAL { return New(NULL); }

  RequestResponseDataType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RequestResponseDataType& from);
  void MergeFrom(const RequestResponseDataType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RequestResponseDataType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef RequestResponseDataType_RequestType RequestType;
  static const RequestType MIN_UNVAILD_TYPE =
    RequestResponseDataType_RequestType_MIN_UNVAILD_TYPE;
  static const RequestType TARGET_CURVE_TYPE =
    RequestResponseDataType_RequestType_TARGET_CURVE_TYPE;
  static const RequestType ENABLE_AUTO_DRIVE_TYPE =
    RequestResponseDataType_RequestType_ENABLE_AUTO_DRIVE_TYPE;
  static const RequestType ENABLE_CAMERA_TYPE =
    RequestResponseDataType_RequestType_ENABLE_CAMERA_TYPE;
  static const RequestType ENABLE_ORIGIN_POINT_CLOUD_TYPE =
    RequestResponseDataType_RequestType_ENABLE_ORIGIN_POINT_CLOUD_TYPE;
  static const RequestType MAX_UNVAILD_TYPE =
    RequestResponseDataType_RequestType_MAX_UNVAILD_TYPE;
  static inline bool RequestType_IsValid(int value) {
    return RequestResponseDataType_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    RequestResponseDataType_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    RequestResponseDataType_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    RequestResponseDataType_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return RequestResponseDataType_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return RequestResponseDataType_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return RequestResponseDataType_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .request_response.TargetCrvuePointType target_curve_points = 4;
  int target_curve_points_size() const;
  void clear_target_curve_points();
  static const int kTargetCurvePointsFieldNumber = 4;
  const ::request_response::TargetCrvuePointType& target_curve_points(int index) const;
  ::request_response::TargetCrvuePointType* mutable_target_curve_points(int index);
  ::request_response::TargetCrvuePointType* add_target_curve_points();
  ::google::protobuf::RepeatedPtrField< ::request_response::TargetCrvuePointType >*
      mutable_target_curve_points();
  const ::google::protobuf::RepeatedPtrField< ::request_response::TargetCrvuePointType >&
      target_curve_points() const;

  // optional string camera_channel_name = 6;
  bool has_camera_channel_name() const;
  void clear_camera_channel_name();
  static const int kCameraChannelNameFieldNumber = 6;
  const ::std::string& camera_channel_name() const;
  void set_camera_channel_name(const ::std::string& value);
  #if LANG_CXX11
  void set_camera_channel_name(::std::string&& value);
  #endif
  void set_camera_channel_name(const char* value);
  void set_camera_channel_name(const char* value, size_t size);
  ::std::string* mutable_camera_channel_name();
  ::std::string* release_camera_channel_name();
  void set_allocated_camera_channel_name(::std::string* camera_channel_name);

  // optional string origin_point_cloud_channel_name = 7;
  bool has_origin_point_cloud_channel_name() const;
  void clear_origin_point_cloud_channel_name();
  static const int kOriginPointCloudChannelNameFieldNumber = 7;
  const ::std::string& origin_point_cloud_channel_name() const;
  void set_origin_point_cloud_channel_name(const ::std::string& value);
  #if LANG_CXX11
  void set_origin_point_cloud_channel_name(::std::string&& value);
  #endif
  void set_origin_point_cloud_channel_name(const char* value);
  void set_origin_point_cloud_channel_name(const char* value, size_t size);
  ::std::string* mutable_origin_point_cloud_channel_name();
  ::std::string* release_origin_point_cloud_channel_name();
  void set_allocated_origin_point_cloud_channel_name(::std::string* origin_point_cloud_channel_name);

  // optional .request_response.ResponseStatusType response_status = 8;
  bool has_response_status() const;
  void clear_response_status();
  static const int kResponseStatusFieldNumber = 8;
  const ::request_response::ResponseStatusType& response_status() const;
  ::request_response::ResponseStatusType* mutable_response_status();
  ::request_response::ResponseStatusType* release_response_status();
  void set_allocated_response_status(::request_response::ResponseStatusType* response_status);

  // required uint64 sequence_id = 1;
  bool has_sequence_id() const;
  void clear_sequence_id();
  static const int kSequenceIdFieldNumber = 1;
  ::google::protobuf::uint64 sequence_id() const;
  void set_sequence_id(::google::protobuf::uint64 value);

  // required .request_response.RequestResponseDataType.RequestType request_type = 2;
  bool has_request_type() const;
  void clear_request_type();
  static const int kRequestTypeFieldNumber = 2;
  ::request_response::RequestResponseDataType_RequestType request_type() const;
  void set_request_type(::request_response::RequestResponseDataType_RequestType value);

  // optional .COWA.NavMsg.VehicleDrive.DrivingMode auto_drive_mode = 5;
  bool has_auto_drive_mode() const;
  void clear_auto_drive_mode();
  static const int kAutoDriveModeFieldNumber = 5;
  ::COWA::NavMsg::VehicleDrive_DrivingMode auto_drive_mode() const;
  void set_auto_drive_mode(::COWA::NavMsg::VehicleDrive_DrivingMode value);

  // @@protoc_insertion_point(class_scope:request_response.RequestResponseDataType)
 private:
  void set_has_sequence_id();
  void clear_has_sequence_id();
  void set_has_request_type();
  void clear_has_request_type();
  void set_has_auto_drive_mode();
  void clear_has_auto_drive_mode();
  void set_has_camera_channel_name();
  void clear_has_camera_channel_name();
  void set_has_origin_point_cloud_channel_name();
  void clear_has_origin_point_cloud_channel_name();
  void set_has_response_status();
  void clear_has_response_status();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::request_response::TargetCrvuePointType > target_curve_points_;
  ::google::protobuf::internal::ArenaStringPtr camera_channel_name_;
  ::google::protobuf::internal::ArenaStringPtr origin_point_cloud_channel_name_;
  ::request_response::ResponseStatusType* response_status_;
  ::google::protobuf::uint64 sequence_id_;
  int request_type_;
  int auto_drive_mode_;
  friend struct protobuf_request_5fresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TargetCrvuePointType

// required double x = 1;
inline bool TargetCrvuePointType::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TargetCrvuePointType::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TargetCrvuePointType::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TargetCrvuePointType::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double TargetCrvuePointType::x() const {
  // @@protoc_insertion_point(field_get:request_response.TargetCrvuePointType.x)
  return x_;
}
inline void TargetCrvuePointType::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:request_response.TargetCrvuePointType.x)
}

// required double y = 2;
inline bool TargetCrvuePointType::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TargetCrvuePointType::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TargetCrvuePointType::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TargetCrvuePointType::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double TargetCrvuePointType::y() const {
  // @@protoc_insertion_point(field_get:request_response.TargetCrvuePointType.y)
  return y_;
}
inline void TargetCrvuePointType::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:request_response.TargetCrvuePointType.y)
}

// -------------------------------------------------------------------

// ResponseStatusType

// required .request_response.ResponseStatusType.RequestStatusEnum reponse_status_code = 1;
inline bool ResponseStatusType::has_reponse_status_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseStatusType::set_has_reponse_status_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseStatusType::clear_has_reponse_status_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseStatusType::clear_reponse_status_code() {
  reponse_status_code_ = 0;
  clear_has_reponse_status_code();
}
inline ::request_response::ResponseStatusType_RequestStatusEnum ResponseStatusType::reponse_status_code() const {
  // @@protoc_insertion_point(field_get:request_response.ResponseStatusType.reponse_status_code)
  return static_cast< ::request_response::ResponseStatusType_RequestStatusEnum >(reponse_status_code_);
}
inline void ResponseStatusType::set_reponse_status_code(::request_response::ResponseStatusType_RequestStatusEnum value) {
  assert(::request_response::ResponseStatusType_RequestStatusEnum_IsValid(value));
  set_has_reponse_status_code();
  reponse_status_code_ = value;
  // @@protoc_insertion_point(field_set:request_response.ResponseStatusType.reponse_status_code)
}

// optional string reponse_status_msg = 2;
inline bool ResponseStatusType::has_reponse_status_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseStatusType::set_has_reponse_status_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseStatusType::clear_has_reponse_status_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseStatusType::clear_reponse_status_msg() {
  reponse_status_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reponse_status_msg();
}
inline const ::std::string& ResponseStatusType::reponse_status_msg() const {
  // @@protoc_insertion_point(field_get:request_response.ResponseStatusType.reponse_status_msg)
  return reponse_status_msg_.GetNoArena();
}
inline void ResponseStatusType::set_reponse_status_msg(const ::std::string& value) {
  set_has_reponse_status_msg();
  reponse_status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_response.ResponseStatusType.reponse_status_msg)
}
#if LANG_CXX11
inline void ResponseStatusType::set_reponse_status_msg(::std::string&& value) {
  set_has_reponse_status_msg();
  reponse_status_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_response.ResponseStatusType.reponse_status_msg)
}
#endif
inline void ResponseStatusType::set_reponse_status_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_reponse_status_msg();
  reponse_status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_response.ResponseStatusType.reponse_status_msg)
}
inline void ResponseStatusType::set_reponse_status_msg(const char* value, size_t size) {
  set_has_reponse_status_msg();
  reponse_status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_response.ResponseStatusType.reponse_status_msg)
}
inline ::std::string* ResponseStatusType::mutable_reponse_status_msg() {
  set_has_reponse_status_msg();
  // @@protoc_insertion_point(field_mutable:request_response.ResponseStatusType.reponse_status_msg)
  return reponse_status_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseStatusType::release_reponse_status_msg() {
  // @@protoc_insertion_point(field_release:request_response.ResponseStatusType.reponse_status_msg)
  clear_has_reponse_status_msg();
  return reponse_status_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseStatusType::set_allocated_reponse_status_msg(::std::string* reponse_status_msg) {
  if (reponse_status_msg != NULL) {
    set_has_reponse_status_msg();
  } else {
    clear_has_reponse_status_msg();
  }
  reponse_status_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reponse_status_msg);
  // @@protoc_insertion_point(field_set_allocated:request_response.ResponseStatusType.reponse_status_msg)
}

// -------------------------------------------------------------------

// RequestResponseDataType

// required uint64 sequence_id = 1;
inline bool RequestResponseDataType::has_sequence_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestResponseDataType::set_has_sequence_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestResponseDataType::clear_has_sequence_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestResponseDataType::clear_sequence_id() {
  sequence_id_ = GOOGLE_ULONGLONG(0);
  clear_has_sequence_id();
}
inline ::google::protobuf::uint64 RequestResponseDataType::sequence_id() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.sequence_id)
  return sequence_id_;
}
inline void RequestResponseDataType::set_sequence_id(::google::protobuf::uint64 value) {
  set_has_sequence_id();
  sequence_id_ = value;
  // @@protoc_insertion_point(field_set:request_response.RequestResponseDataType.sequence_id)
}

// required .request_response.RequestResponseDataType.RequestType request_type = 2;
inline bool RequestResponseDataType::has_request_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RequestResponseDataType::set_has_request_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RequestResponseDataType::clear_has_request_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RequestResponseDataType::clear_request_type() {
  request_type_ = 0;
  clear_has_request_type();
}
inline ::request_response::RequestResponseDataType_RequestType RequestResponseDataType::request_type() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.request_type)
  return static_cast< ::request_response::RequestResponseDataType_RequestType >(request_type_);
}
inline void RequestResponseDataType::set_request_type(::request_response::RequestResponseDataType_RequestType value) {
  assert(::request_response::RequestResponseDataType_RequestType_IsValid(value));
  set_has_request_type();
  request_type_ = value;
  // @@protoc_insertion_point(field_set:request_response.RequestResponseDataType.request_type)
}

// repeated .request_response.TargetCrvuePointType target_curve_points = 4;
inline int RequestResponseDataType::target_curve_points_size() const {
  return target_curve_points_.size();
}
inline void RequestResponseDataType::clear_target_curve_points() {
  target_curve_points_.Clear();
}
inline const ::request_response::TargetCrvuePointType& RequestResponseDataType::target_curve_points(int index) const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.target_curve_points)
  return target_curve_points_.Get(index);
}
inline ::request_response::TargetCrvuePointType* RequestResponseDataType::mutable_target_curve_points(int index) {
  // @@protoc_insertion_point(field_mutable:request_response.RequestResponseDataType.target_curve_points)
  return target_curve_points_.Mutable(index);
}
inline ::request_response::TargetCrvuePointType* RequestResponseDataType::add_target_curve_points() {
  // @@protoc_insertion_point(field_add:request_response.RequestResponseDataType.target_curve_points)
  return target_curve_points_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::request_response::TargetCrvuePointType >*
RequestResponseDataType::mutable_target_curve_points() {
  // @@protoc_insertion_point(field_mutable_list:request_response.RequestResponseDataType.target_curve_points)
  return &target_curve_points_;
}
inline const ::google::protobuf::RepeatedPtrField< ::request_response::TargetCrvuePointType >&
RequestResponseDataType::target_curve_points() const {
  // @@protoc_insertion_point(field_list:request_response.RequestResponseDataType.target_curve_points)
  return target_curve_points_;
}

// optional .COWA.NavMsg.VehicleDrive.DrivingMode auto_drive_mode = 5;
inline bool RequestResponseDataType::has_auto_drive_mode() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RequestResponseDataType::set_has_auto_drive_mode() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RequestResponseDataType::clear_has_auto_drive_mode() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RequestResponseDataType::clear_auto_drive_mode() {
  auto_drive_mode_ = 0;
  clear_has_auto_drive_mode();
}
inline ::COWA::NavMsg::VehicleDrive_DrivingMode RequestResponseDataType::auto_drive_mode() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.auto_drive_mode)
  return static_cast< ::COWA::NavMsg::VehicleDrive_DrivingMode >(auto_drive_mode_);
}
inline void RequestResponseDataType::set_auto_drive_mode(::COWA::NavMsg::VehicleDrive_DrivingMode value) {
  assert(::COWA::NavMsg::VehicleDrive_DrivingMode_IsValid(value));
  set_has_auto_drive_mode();
  auto_drive_mode_ = value;
  // @@protoc_insertion_point(field_set:request_response.RequestResponseDataType.auto_drive_mode)
}

// optional string camera_channel_name = 6;
inline bool RequestResponseDataType::has_camera_channel_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestResponseDataType::set_has_camera_channel_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestResponseDataType::clear_has_camera_channel_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestResponseDataType::clear_camera_channel_name() {
  camera_channel_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_channel_name();
}
inline const ::std::string& RequestResponseDataType::camera_channel_name() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.camera_channel_name)
  return camera_channel_name_.GetNoArena();
}
inline void RequestResponseDataType::set_camera_channel_name(const ::std::string& value) {
  set_has_camera_channel_name();
  camera_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_response.RequestResponseDataType.camera_channel_name)
}
#if LANG_CXX11
inline void RequestResponseDataType::set_camera_channel_name(::std::string&& value) {
  set_has_camera_channel_name();
  camera_channel_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_response.RequestResponseDataType.camera_channel_name)
}
#endif
inline void RequestResponseDataType::set_camera_channel_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_camera_channel_name();
  camera_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_response.RequestResponseDataType.camera_channel_name)
}
inline void RequestResponseDataType::set_camera_channel_name(const char* value, size_t size) {
  set_has_camera_channel_name();
  camera_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_response.RequestResponseDataType.camera_channel_name)
}
inline ::std::string* RequestResponseDataType::mutable_camera_channel_name() {
  set_has_camera_channel_name();
  // @@protoc_insertion_point(field_mutable:request_response.RequestResponseDataType.camera_channel_name)
  return camera_channel_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestResponseDataType::release_camera_channel_name() {
  // @@protoc_insertion_point(field_release:request_response.RequestResponseDataType.camera_channel_name)
  clear_has_camera_channel_name();
  return camera_channel_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestResponseDataType::set_allocated_camera_channel_name(::std::string* camera_channel_name) {
  if (camera_channel_name != NULL) {
    set_has_camera_channel_name();
  } else {
    clear_has_camera_channel_name();
  }
  camera_channel_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_channel_name);
  // @@protoc_insertion_point(field_set_allocated:request_response.RequestResponseDataType.camera_channel_name)
}

// optional string origin_point_cloud_channel_name = 7;
inline bool RequestResponseDataType::has_origin_point_cloud_channel_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestResponseDataType::set_has_origin_point_cloud_channel_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestResponseDataType::clear_has_origin_point_cloud_channel_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestResponseDataType::clear_origin_point_cloud_channel_name() {
  origin_point_cloud_channel_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_origin_point_cloud_channel_name();
}
inline const ::std::string& RequestResponseDataType::origin_point_cloud_channel_name() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
  return origin_point_cloud_channel_name_.GetNoArena();
}
inline void RequestResponseDataType::set_origin_point_cloud_channel_name(const ::std::string& value) {
  set_has_origin_point_cloud_channel_name();
  origin_point_cloud_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
}
#if LANG_CXX11
inline void RequestResponseDataType::set_origin_point_cloud_channel_name(::std::string&& value) {
  set_has_origin_point_cloud_channel_name();
  origin_point_cloud_channel_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
}
#endif
inline void RequestResponseDataType::set_origin_point_cloud_channel_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_origin_point_cloud_channel_name();
  origin_point_cloud_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
}
inline void RequestResponseDataType::set_origin_point_cloud_channel_name(const char* value, size_t size) {
  set_has_origin_point_cloud_channel_name();
  origin_point_cloud_channel_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
}
inline ::std::string* RequestResponseDataType::mutable_origin_point_cloud_channel_name() {
  set_has_origin_point_cloud_channel_name();
  // @@protoc_insertion_point(field_mutable:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
  return origin_point_cloud_channel_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestResponseDataType::release_origin_point_cloud_channel_name() {
  // @@protoc_insertion_point(field_release:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
  clear_has_origin_point_cloud_channel_name();
  return origin_point_cloud_channel_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestResponseDataType::set_allocated_origin_point_cloud_channel_name(::std::string* origin_point_cloud_channel_name) {
  if (origin_point_cloud_channel_name != NULL) {
    set_has_origin_point_cloud_channel_name();
  } else {
    clear_has_origin_point_cloud_channel_name();
  }
  origin_point_cloud_channel_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), origin_point_cloud_channel_name);
  // @@protoc_insertion_point(field_set_allocated:request_response.RequestResponseDataType.origin_point_cloud_channel_name)
}

// optional .request_response.ResponseStatusType response_status = 8;
inline bool RequestResponseDataType::has_response_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestResponseDataType::set_has_response_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestResponseDataType::clear_has_response_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestResponseDataType::clear_response_status() {
  if (response_status_ != NULL) response_status_->::request_response::ResponseStatusType::Clear();
  clear_has_response_status();
}
inline const ::request_response::ResponseStatusType& RequestResponseDataType::response_status() const {
  // @@protoc_insertion_point(field_get:request_response.RequestResponseDataType.response_status)
  return response_status_ != NULL ? *response_status_
                         : *::request_response::ResponseStatusType::internal_default_instance();
}
inline ::request_response::ResponseStatusType* RequestResponseDataType::mutable_response_status() {
  set_has_response_status();
  if (response_status_ == NULL) {
    response_status_ = new ::request_response::ResponseStatusType;
  }
  // @@protoc_insertion_point(field_mutable:request_response.RequestResponseDataType.response_status)
  return response_status_;
}
inline ::request_response::ResponseStatusType* RequestResponseDataType::release_response_status() {
  // @@protoc_insertion_point(field_release:request_response.RequestResponseDataType.response_status)
  clear_has_response_status();
  ::request_response::ResponseStatusType* temp = response_status_;
  response_status_ = NULL;
  return temp;
}
inline void RequestResponseDataType::set_allocated_response_status(::request_response::ResponseStatusType* response_status) {
  delete response_status_;
  response_status_ = response_status;
  if (response_status) {
    set_has_response_status();
  } else {
    clear_has_response_status();
  }
  // @@protoc_insertion_point(field_set_allocated:request_response.RequestResponseDataType.response_status)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace request_response

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::request_response::ResponseStatusType_RequestStatusEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::request_response::ResponseStatusType_RequestStatusEnum>() {
  return ::request_response::ResponseStatusType_RequestStatusEnum_descriptor();
}
template <> struct is_proto_enum< ::request_response::RequestResponseDataType_RequestType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::request_response::RequestResponseDataType_RequestType>() {
  return ::request_response::RequestResponseDataType_RequestType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_request_5fresponse_2eproto__INCLUDED
